haraka:
  ports:
  - 25:25/tcp
  - 587:587/tcp
  - 465:465/tcp
  - 143:143/tcp
  - 993:993/tcp
  environment:
    HOSTNAME: ${hostname}
    MYSQL_HOST: mysql
    MYSQL_DATABASE: "${mysql_database}"
    MYSQL_USER: "${mysql_user}"
    MYSQL_PASSWORD: "${mysql_password}"    
  external_links:
    - ${database_link}:mysql
  labels:
    io.rancher.sidekicks: dovecot,spamassassin,clamav,mail-data
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  image: flowman/haraka
  volumes_from:
  - mail-data
mail-data:
  environment:
    HOSTNAME: ${hostname}
  labels:
    io.rancher.container.start_once: 'true'
  command:
  - /bin/true
  image: flowman/haraka
  volumes:
  - /data
  net: none
clamav:
  labels:
    io.rancher.container.hostname_override: container_name
  image: flowman/clamav
  net: container:haraka
dovecot:
  environment:
    MYSQL_HOST: mysql
    MYSQL_DATABASE: "${mysql_database}"
    MYSQL_USER: "${mysql_user}"
    MYSQL_PASSWORD: "${mysql_password}"
  labels:
    io.rancher.container.hostname_override: container_name
  image: flowman/dovecot
  volumes_from:
  - mail-data
  net: container:haraka
spamassassin:
  labels:
    io.rancher.container.hostname_override: container_name
  image: flowman/spamassassin
  net: container:haraka