.catalog:
  name: "Haraka"
  version: 2.7.3-rancher1
  description: |
    A modern, high performance, flexible SMTP server
  questions:
    - variable: "hostname"
      description: "DNS hostname for the mail server."
      label: "Hostname:"
      default: "mail.dev"
      required: true
      type: "string"    
    - variable: "mysql_database"
      type: string
      required: true
      label: "MySQL Database Name"
      description: "MySQL database to create"
    - variable: "mysql_user"
      type: string
      required: true
      description: "MySQL user for the created database"
      label: "MySQL DB User"
    - variable: "mysql_password"
      type: string
      required: true
      label: "MySQL DB Password"
      description: "Password for the MySQL user of the created database"      
    - variable: "database_link"
      description: |
        stack/service link or external service link to database.
      label: "Database stack/service"
      default: ""
      required: true
      type: "service"